version: '3'
services:
  kafka-fast-data-dev:
    image: landoop/fast-data-dev
    ports:
      - "3030:3030" # UI
      - "9092:9092" # Brocker
      - "8081:8081" # Schema Registry

    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_CONNECT: zookeeper:2181
      RUNTESTS: 0
      SAMPLEDATA: 0